# Generated by Django 5.0.3 on 2024-03-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Menu_item'},
        ),
    ]
